<?php
/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
namespace Swiftriver\Core;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for ParserFactory.
 * Generated by PHPUnit on 2010-03-13 at 09:23:18.
 */
class SwiftriverSourceParsingServiceTest extends \PHPUnit_Framework_TestCase {
    /**
     * Include the following files:
     * IParser interface
     */
    protected function setUp() {
        include_once(dirname(__FILE__)."/../../../Setup.php");
    }
    
    public function testReturnAllAvailableParsers() {
        $service = new \Swiftriver\Core\Modules\SiSPS\SwiftriverSourceParsingService();
        $parsers = $service->ListAvailableParsers();
        $this->assertEquals(3, count($parsers));
        $RSSTypes = $parsers[0]->ListSubTypes();
        $this->assertEquals("Blogs", $RSSTypes[0]);
    }

}
?>
